version: '3'

services:
  db:
    image: postgres:14.3
    restart: always
    container_name: postgres-db
    ports:
      - 5432:5432 # binding --> local port : container port
    environment: # https://hub.docker.com/_/postgres#:~:text=have%20found%20useful.-,Environment%20Variables,-The%20PostgreSQL%20image
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./postgres:/var/lib/postgresql/data # binding --> local dir : container dir
