version: '3'

services:
  db:
    image: mongo:5
    restart: always
    container_name: mongo-db
    ports:
      - 27017:27017 # binding --> local port : container port
    environment:
      MONGOBD_DATABASE: pokemonsdb
    volumes:
      - ./mongo:/data/db # binding --> local dir : container dir
